# Generated by Django 5.1.7 on 2025-08-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
