# Generated by Django 5.1.7 on 2025-08-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionitem_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='production_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_items', to='production.productionrecord'),
        ),
    ]
