# Generated by Django 5.1.7 on 2025-08-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productionitem_production_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
