# Generated by Django 5.1.7 on 2025-08-08 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_current_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock_threshold', models.IntegerField(default=0)),
                ('max_stock_capacity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_settings', to='products.product')),
            ],
        ),
    ]
