# Generated by Django 5.1.7 on 2025-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
